# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '{{cookiecutter.app_name}}' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for {{cookiecutter.app_name}}

  target '{{cookiecutter.app_name}}Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
