platform :ios, '10.0'

target '{{cookiecutter.app_name}}' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  target '{{cookiecutter.app_name}}Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2'
    pod 'Nimble', '~> 7.0'
  end

end
